				'Juggling', 'Walking', 'Running', 'Sprinting', 'Debating', 'Killing', 'Murdering', 'Slaughtering', 'Destroying',
				'Swapping', 'Distracting', 'Playing', 'Disposing', 'Negotiating', 'Eating', 'Following', 'Jingling', 'Returning',
				'Standing', 'Sleeping', 'Branding', 'Meeting', 'Dreaming', 'Singing', 'Waking', 'Loving', 'Skipping', 'Rhyming',
				'Chasing', 'Shadowing', 'Stalking', 'Going', 'Leaving', 'Exiting', 'Mourning', 'Disappearing', 'Calling',
				'Reaching', 'Hopping', 'Waving', 'Circling', 'Driving', 'Laughing', 'Making', 'Hiding', 'Looking', 'Courting',
				'Humming', 'Holding', 'Counting', 'Numbering', 'Dancing', 'Lying', 'Questioning', 'Reversing', 'Tailing', 'Whistling',
				'Theorising', 'Coding', 'Starting', 'Beginning', 'Ending', 'Trying', 'Recording', 'Pouring', 'Scattering', 'Vlogging', 
        		'Dodging', 'Ducking', 'Swimming', 'Winking', 'Kissing', 'Snogging', 'Shrugging', 'Waking', 'Reading', 'Writing', 'Listening', 
        		'Speaking', 'Interviewing', 'Selling', 'Buying', 'Exchanging', 'Bartering', 'Discounting', 'Bargaining', 'Sailing', 'Haggling', 
        		'Babbling', 'Conversing', 'Communicating', 'Draining', 'Training', 'Seeping', 'Washing', 'Laundering', 'Merging', 'Spelling', 
        		'Escaping', 'Rescuing', 'Hiding', 'Revealing', 'Wandering', 'Wondering', 'Describing', 'Articulating', 'Learning', 'Teaching', 
        		'Assessing', 'Correcting', 'Marking', 'Diminishing', 'Belittling', 'Instructing', 'Bribing', 'Suing', 'Claiming', 'Crying', 'Exploring', 
        		'Exploding', 'Loading', 'Gaming', 'Moaning', 'Working', 'Relaxing', 'Refreshing', 'Reenergising', 'Self-destructing', 'Monetising', 
        		'Schooling', 'Transferring', 'Telling', 'Dying', 'Living', 'Dyeing', 'Drying', 'Diving', 'Boxing', 'Improving', 'Riding', 'Cycling', 
        		'Hitching', 'Skating', 'Flying', 'Soaring', 'Gliding', 'Boating', 'Cruising', 'Seeing', 'Believing', 'Touching', 'Humouring', 'Sensing', 
        		'Hearing', 'Smelling', 'Spying', 'Frying', 'Roasting', 'Bludgeoning', 'Bleeding', 'Swerving', 'Begrudging', 'Becoming', 'Tying', 'Smiling', 
        		'Reflecting', 'Doing', 'Sewing', 'Knitting', 'Crocheting', 'Corroding', 'Dissolving', 'Erroding', 'Melting', 'Sieving', 'Baking', 'Cooking', 
        		'Bathing', 'Showering', 'Showing', 'Drinking', 'Consuming', 'Imbibing', 'Partaking', 'Soliciting', 'Reserving', 'Booking', 'Conserving', 'Responding', 
        		'Advocating', 'Retorting', 'Putting', 'Golfing', 'Fishing', 'Farming', 'Anchoring', 'Serving', 'Checking', 'Telephoning', 'Watching', 'Whispering', 
        		'Misleading', 'Leading', 'Travelling', 'Transporting', 'Translating', 'Troubling', 'Riddling', 'Fiddling', 'Fidgeting', 'Groping', 'Fondling', 
        		'Fornicating', 'Massaging', 'Eyeing', 'Being', 'Using', 'Dragging', 'Scribing', 'Introducing', 'Concluding', 'Creating', 'Debunking', 'Defibrilating', 
        		'Testing', 'Admonishing', 'Organising', 'Trespassing', 'Relating', 'Resting', 'Napping', 'Reporting', 'Experimenting', 'Sustaining', 'Surprising', 
        		'Narrating', 'Parking', 'Panting', 'Stroking', 'Reasoning', 'Typing', 'Tugging', 'Tilling', 'Totting', 'Toddling', 'Tooting', 'Tipping', 'Taking', 
        		'Trekking', 'Turning', 'Tracing', 'Analising', 'Criticising', 'Dispelling', 'Corrupting', 'Characterising', 'Falling', 'Factoring', 'Accounting',
        		'Lecturing', 'Liasing', 'Betraying', 'Prophesying', 'Converting', 'Demonising', 'Demonstrating', 'Disentangling', 'Crossing', 'Lining', 'Pouncing', 
        		'Fingering', 'Pinning', 'Prying', 'Kneading', 'Knowing', 'Exclaiming', 'Helping', 'Heeding', 'Recruiting', 'Battling', 'Outsourcing', 'Crystalising', 
        		'Building', 'Celebrating', 'Regulating', 'Struggling', 'Navigating', 'Disclosing', 'Freeing', 'Missing', 'Microwaving', 'Shutting', 'Lifting', 'Leaning', 
        		'Lording', 'Hoarding', 'Lurching', 'Shouting', 'Screaming', 'Swinging', 'Flailing', 'Failing', 'Decaying', 'Deliberating', 'Deeming', 'Judging',
        		'Jumping', 'Bouncing', 'Wallowing', 'Wanting', 'Wishing', 'Whirling', 'Trailing', 'Tailoring', 'Butchering', 'Rectifying', 'Wriggling', 'Gambling', 
        		'Smoking', 'Injecting', 'Enjoying', 'Enducing', 'Injuring', 'Annoying', 'Arguing', 'Discussing', 'Convincing', 'Flirting', 'Adoring', 'Worshipping', 
        		'Stripping', 'Blowing', 'Penetrating', 'Pecking', 'Humping', 'Biting', 'Spanking', 'Slapping', 'Rubbing', 'Fading', 'Drifting', 'Parting', 'Promising', 
        		'Happening', 'Willing', 'Yawning', 'Boring', 'Programming', 'Computing', 'Hugging', 'Cuddling', 'Roaming', 'Teetering', 'Finding', 'Setting', 'Frustrating', 
        		'Teething', 'Snarling', 'Barking', 'Mewing', 'Tapping', 'Drawing', 'Taping', 'Remarking', 'Resizing', 'Packaging', 'Disagreeing', 'Smirking', 'Staring', 
        		'Losing', 'Warning', 'Worrying', 'Presenting', 'Portraying', 'Joking', 