var object = ["Cane", "Kite", "Computer", "Television", "Car"];
var arrayToCheckBy = [];
var game = document.getElementById('game');
var word = document.getElementById('wordToDescribe');
var timer = document.getElementById('timer');
var startButton = document.getElementById('start');
var gotIt = document.getElementById('gotIt');
var pass = document.getElementById('pass')
var numberForTimer = 30;
var timesUpMessage = "Time's up!";
var noOfPasses = 0;
